### ISSUE TITLE
Date format is not applied

### ISSUE THREAD

**Issue by kitbs** [dillingham/nova-grouped-field#5]
Thanks for a great field that I have a lot of use cases for!

I was hoping to use it to display a date range which I have stored in two separate fields:

```php
// The editable start date field, only on forms
Date::make(__('Start Date'), 'date_from')
    ->format('D MMM YYYY')
    ->onlyOnForms()
    ->rules(['required', 'date']),

// The editable end date field, only on forms
Date::make(__('End Date'), 'date_to')
    ->format('D MMM YYYY')
    ->onlyOnForms()
    ->rules(['required', 'date', 'after:date_from']),

// Both fields combined, for the index and detail views only
Grouped::make(__('Dates'))->fields([
    Date::make(__('Start Date'), 'date_from')
        ->format('D MMM YYYY'),

    Date::make(__('End Date'), 'date_to')
        ->format('D MMM YYYY'),
])->separator(' – '),
```

The grouped date fields on the detail (and index) views display as:
![image](https://user-images.githubusercontent.com/4569320/55958644-1414c780-5c61-11e9-9d25-e58252f6330b.png)

In contrast to how the individual date fields appear (if I remove `->onlyOnForms()`):
![image](https://user-images.githubusercontent.com/4569320/55958681-30b0ff80-5c61-11e9-95cd-4afdc1328810.png)

Am I doing anything wrong with the code above? I guess I could do something like this instead, which does work, but it seems redundant to have to handle the formatting on the server side:
```php
Date::make(__('Start Date'), 'date_from', function($date) {
    return $date->format('j M Y');
}),
```

Cheers

**Comment by wize-wiz** [comment]
`Date` and `DateTime` seems to have problems applying attributes in general throughout Nova. Using the `resolveUsing` callback should work as expected.

```
Grouped::make('Combined')->fields([
    Date::make(__('Start Date'), 'date_from')
        ->resolveUsing(function($date) {
                return $date->format('D MMM YYYY');
            }),

    Date::make(__('End Date'), 'date_to')
        ->resolveUsing(function($date) {
                return $date->format('D MMM YYYY');
            }),
]);

```
